# Engine Framework - Shared Kubernetes Configuration

# Base Deployment Template
# Usage: Copy to k8s/deployment.yaml and customize per repository

apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-engine-core
  labels:
    app: engine-engine-core
    component: engine_core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: engine-engine-core
  template:
    metadata:
      labels:
        app: engine-engine-core
        component: engine_core
    spec:
      containers:
      - name: app
        image: ghcr.io/engine-framework/engine-core:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: engine-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: engine-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
